import type { Car } from "./types";

export const CARS: Car[] = [
  {
    id: 1,
    name: "Mercedes-Benz S-Class",
    year: 2024,
    price: 115000,
    mileage: 4200,
    fuel: "Petrol",
    category: "Sedan",
    brand: "Mercedes-Benz",
    available: true,
    badge: "Featured",
    horsepower: 429,
    torque: 384,
    engine: "3.0L Inline-6 Turbo",
    transmission: "9-Speed Automatic",
    drivetrain: "RWD",
    topSpeed: 155,
    zeroToSixty: 4.9,
    fuelType: "Premium Petrol",
    mpg: "22 city / 29 hwy",
    seating: 5,
    infotainment: "MBUX Hyperscreen 56-inch",
    safetyFeatures: ["Active Brake Assist", "PRE-SAFE", "Lane Keeping Assist", "Blind Spot Assist", "Night Vision"],
    colors: [
      { name: "Obsidian Black Metallic", hex: "#0d0d0d", img: "" },
      { name: "Polar White",             hex: "#f4f4f0", img: "" },
      { name: "Selenite Grey Metallic",  hex: "#7a7a7a", img: "" },
      { name: "Cavansite Blue Metallic", hex: "#1e3d5c", img: "" },
      { name: "Designo Hyacinth Red",    hex: "#6b1a2a", img: "" },
      { name: "Emerald Green Metallic",  hex: "#1a3a28", img: "" },
    ],
    specs: {
      engine: "3.0L Inline-6 Turbo",
      power: "429 hp",
      torque: "384 lb-ft",
      transmission: "9-Speed Auto",
      drivetrain: "RWD",
      seats: 5,
    },
    description: "The pinnacle of automotive luxury. The S-Class sets the benchmark for comfort, technology, and refinement — a moving sanctuary for those who demand the very best. The 2024 model features the revolutionary MBUX Hyperscreen and a cabin that anticipates your every need.",
    images: [
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=1200&q=90&auto=format&fit=crop",
    ],
  },
  {
    id: 2,
    name: "BMW X7 xDrive50i",
    year: 2024,
    price: 98500,
    mileage: 6100,
    fuel: "Petrol",
    category: "SUV",
    brand: "BMW",
    available: true,
    badge: "New Arrival",
    horsepower: 523,
    torque: 553,
    engine: "4.4L V8 Twin-Turbo",
    transmission: "8-Speed Automatic",
    drivetrain: "AWD",
    topSpeed: 155,
    zeroToSixty: 4.5,
    fuelType: "Premium Petrol",
    mpg: "16 city / 21 hwy",
    seating: 7,
    infotainment: "BMW iDrive 8 with 14.9\" Curved Display",
    safetyFeatures: ["Active Driving Assistant Pro", "Parking Assistant Plus", "Surround View", "Collision Warning"],
    colors: [
      { name: "Carbon Black Metallic",  hex: "#141414", img: "" },
      { name: "Alpine White",           hex: "#f0f0ec", img: "" },
      { name: "Phytonic Blue Metallic", hex: "#2a4a6e", img: "" },
      { name: "Mineral White Metallic", hex: "#e4e4e0", img: "" },
      { name: "Sparkling Copper Grey",  hex: "#7a5a3a", img: "" },
      { name: "Dravit Grey Metallic",   hex: "#4a4a4a", img: "" },
    ],
    specs: {
      engine: "4.4L V8 Twin-Turbo",
      power: "523 hp",
      torque: "553 lb-ft",
      transmission: "8-Speed Auto",
      drivetrain: "AWD",
      seats: 7,
    },
    description: "Commanding presence meets effortless performance. The X7 redefines what a luxury SUV can be — spacious, powerful, and unmistakably BMW. Three rows of hand-stitched leather, panoramic sky lounge roof, and the latest iDrive 8 system.",
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=1200&q=90&auto=format&fit=crop",
    ],
  },
  {
    id: 3,
    name: "Porsche 911 Carrera S",
    year: 2023,
    price: 142000,
    mileage: 8900,
    fuel: "Petrol",
    category: "Sport",
    brand: "Porsche",
    available: true,
    badge: "Low Mileage",
    horsepower: 443,
    torque: 390,
    engine: "3.0L Flat-6 Twin-Turbo",
    transmission: "8-Speed PDK",
    drivetrain: "RWD",
    topSpeed: 191,
    zeroToSixty: 3.5,
    fuelType: "Premium Petrol",
    mpg: "18 city / 24 hwy",
    seating: 4,
    infotainment: "Porsche Communication Management 12\"",
    safetyFeatures: ["Porsche Stability Management", "PCCB Ceramic Brakes", "Lane Change Assist", "Night Vision"],
    colors: [
      { name: "GT Silver Metallic",    hex: "#b8b8b8", img: "" },
      { name: "Guards Red",            hex: "#c8001e", img: "" },
      { name: "Jet Black Metallic",    hex: "#0d0d0d", img: "" },
      { name: "Racing Yellow",         hex: "#f0c000", img: "" },
      { name: "Gentian Blue Metallic", hex: "#1a2e50", img: "" },
      { name: "Chalk",                 hex: "#d8d4c8", img: "" },
      { name: "Aventurine Green",      hex: "#2a4a2a", img: "" },
    ],
    specs: {
      engine: "3.0L Flat-6 Twin-Turbo",
      power: "443 hp",
      torque: "390 lb-ft",
      transmission: "8-Speed PDK",
      drivetrain: "RWD",
      seats: 4,
    },
    description: "Sixty years of motorsport DNA distilled into one iconic silhouette. The 911 Carrera S is not just a sports car — it is the sports car. Every surface, every system, every sound engineered to deliver an experience that is impossible to replicate.",
    images: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611821064430-0d40291d0f0b?w=1200&q=90&auto=format&fit=crop",
    ],
  },
  {
    id: 4,
    name: "Audi Q8 e-tron",
    year: 2024,
    price: 87000,
    mileage: 2100,
    fuel: "Electric",
    category: "SUV",
    brand: "Audi",
    available: true,
    badge: "Electric",
    horsepower: 402,
    torque: 490,
    engine: "Dual Electric Motor",
    transmission: "Single-Speed",
    drivetrain: "AWD",
    topSpeed: 124,
    zeroToSixty: 5.6,
    fuelType: "Electric",
    range: "300 miles",
    seating: 5,
    infotainment: "MMI Navigation Plus with 10.1\" & 8.6\" Touchscreens",
    safetyFeatures: ["Audi Pre Sense", "Adaptive Cruise Assist", "360° Camera", "Exit Warning"],
    colors: [
      { name: "Mythos Black Metallic",   hex: "#0d0d0d", img: "" },
      { name: "Glacier White Metallic",  hex: "#f0f0ec", img: "" },
      { name: "Chronos Grey Metallic",   hex: "#686868", img: "" },
      { name: "Plasma Blue",             hex: "#1c3860", img: "" },
      { name: "Typhoon Grey",            hex: "#4a4a52", img: "" },
      { name: "Soneira Brown Metallic",  hex: "#5a3a28", img: "" },
    ],
    specs: {
      engine: "Dual Electric Motor",
      power: "402 hp",
      torque: "490 lb-ft",
      transmission: "Single-Speed",
      drivetrain: "AWD",
      seats: 5,
    },
    description: "The future of luxury SUVs is electric. The Q8 e-tron delivers Audi's signature quattro performance with zero emissions and a 300-mile range. Virtual exterior mirrors, matrix LED headlights, and a cabin of unmatched refinement.",
    images: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=90&auto=format&fit=crop",
    ],
  },
  {
    id: 5,
    name: "Range Rover Autobiography",
    year: 2024,
    price: 178000,
    mileage: 1500,
    fuel: "Hybrid",
    category: "SUV",
    brand: "Land Rover",
    available: true,
    badge: "Premium",
    horsepower: 530,
    torque: 553,
    engine: "4.4L V8 Twin-Turbo",
    transmission: "8-Speed Automatic",
    drivetrain: "AWD",
    topSpeed: 155,
    zeroToSixty: 4.6,
    fuelType: "Hybrid",
    mpg: "19 city / 26 hwy",
    seating: 5,
    infotainment: "Pivi Pro 13.1\" Curved Touchscreen",
    safetyFeatures: ["ClearSight Ground View", "Wade Sensing", "Terrain Response 2", "Emergency Braking"],
    colors: [
      { name: "Santorini Black",       hex: "#0f0f0f", img: "" },
      { name: "Fuji White",            hex: "#f4f4f0", img: "" },
      { name: "Carpathian Grey",       hex: "#484848", img: "" },
      { name: "Portofino Blue",        hex: "#1a2e4a", img: "" },
      { name: "Charente Grey",         hex: "#8a8a82", img: "" },
      { name: "Rossello Red",          hex: "#7a1a1a", img: "" },
      { name: "Gondwana Stone",        hex: "#c8b89a", img: "" },
    ],
    specs: {
      engine: "4.4L V8 Twin-Turbo",
      power: "530 hp",
      torque: "553 lb-ft",
      transmission: "8-Speed Auto",
      drivetrain: "AWD",
      seats: 5,
    },
    description: "The definitive luxury SUV. The Range Rover Autobiography combines unmatched off-road capability with a cabin that rivals the finest private jets. Executive rear seating, 23-speaker Meridian Signature sound, and a presence that commands every road.",
    images: [
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=90&auto=format&fit=crop",
    ],
  },
  {
    id: 6,
    name: "Bentley Continental GT",
    year: 2023,
    price: 225000,
    mileage: 5600,
    fuel: "Petrol",
    category: "Sport",
    brand: "Bentley",
    available: false,
    badge: "Sold",
    horsepower: 626,
    torque: 664,
    engine: "6.0L W12 Twin-Turbo",
    transmission: "8-Speed DCT",
    drivetrain: "AWD",
    topSpeed: 207,
    zeroToSixty: 3.6,
    fuelType: "Premium Petrol",
    mpg: "12 city / 20 hwy",
    seating: 4,
    infotainment: "Bentley Rotating Display 12.3\"",
    safetyFeatures: ["Night Vision", "Traffic Sign Recognition", "Rear Cross Traffic Alert", "Head-Up Display"],
    colors: [
      { name: "Beluga",              hex: "#0a0a0a", img: "" },
      { name: "Ghost White",         hex: "#f6f4f0", img: "" },
      { name: "Viridian",            hex: "#1a3a28", img: "" },
      { name: "Moroccan Blue",       hex: "#1a2848", img: "" },
      { name: "Barnato Green",       hex: "#2a4a1a", img: "" },
      { name: "Pale Brodgar",        hex: "#c8c0b0", img: "" },
      { name: "Candy Red",           hex: "#aa1a1a", img: "" },
    ],
    specs: {
      engine: "6.0L W12 Twin-Turbo",
      power: "626 hp",
      torque: "664 lb-ft",
      transmission: "8-Speed DCT",
      drivetrain: "AWD",
      seats: 4,
    },
    description: "Hand-crafted in Crewe, England. The Continental GT is the grand tourer that defines the genre — effortless power wrapped in the finest materials on earth. 15 hides of leather, 18 veneers of wood, and a W12 engine that makes 207 mph feel serene.",
    images: [
      "https://images.unsplash.com/photo-1563720223185-11003d516935?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1542362567-b07e54358753?w=1200&q=90&auto=format&fit=crop",
    ],
  },
  {
    id: 7,
    name: "Tesla Model S Plaid",
    year: 2024,
    price: 94990,
    mileage: 3300,
    fuel: "Electric",
    category: "Sedan",
    brand: "Tesla",
    available: true,
    badge: "Electric",
    horsepower: 1020,
    torque: 1050,
    engine: "Tri-Motor Electric",
    transmission: "Single-Speed",
    drivetrain: "AWD",
    topSpeed: 200,
    zeroToSixty: 1.99,
    fuelType: "Electric",
    range: "396 miles",
    seating: 5,
    infotainment: "17\" Cinematic Touchscreen + 12.3\" Rear Display",
    safetyFeatures: ["Autopilot", "Full Self-Driving Capability", "Automatic Emergency Braking", "Side Collision Warning"],
    colors: [
      { name: "Stealth Grey",         hex: "#383838", img: "" },
      { name: "Pearl White Multi-Coat",hex: "#f4f4f0", img: "" },
      { name: "Midnight Black",       hex: "#0a0a0a", img: "" },
      { name: "Ultra Red",            hex: "#8c1a1a", img: "" },
      { name: "Deep Blue Metallic",   hex: "#1a2a4a", img: "" },
    ],
    specs: {
      engine: "Tri-Motor Electric",
      power: "1,020 hp",
      torque: "1,050 lb-ft",
      transmission: "Single-Speed",
      drivetrain: "AWD",
      seats: 5,
    },
    description: "0–60 in 1.99 seconds. The Model S Plaid is the fastest production sedan ever built — a technological marvel that redefines what performance means. Yoke steering, 17-inch cinematic display, and a range of 396 miles on a single charge.",
    images: [
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1571987502227-9231b837d92a?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1536700503339-1e4b06520771?w=1200&q=90&auto=format&fit=crop",
    ],
  },
  {
    id: 8,
    name: "Lamborghini Urus S",
    year: 2024,
    price: 248000,
    mileage: 1200,
    fuel: "Petrol",
    category: "SUV",
    brand: "Lamborghini",
    available: true,
    badge: "Exotic",
    horsepower: 657,
    torque: 627,
    engine: "4.0L V8 Twin-Turbo",
    transmission: "8-Speed Automatic",
    drivetrain: "AWD",
    topSpeed: 190,
    zeroToSixty: 3.5,
    fuelType: "Premium Petrol",
    mpg: "12 city / 17 hwy",
    seating: 5,
    infotainment: "Lamborghini ANIMA with 10.1\" + 8.4\" Touchscreens",
    safetyFeatures: ["Lamborghini Rear View Camera", "Park Assist", "Night Vision", "Blind Spot Monitoring"],
    colors: [
      { name: "Nero Noctis",       hex: "#0a0a0a", img: "" },
      { name: "Bianco Icarus",     hex: "#f4f4f0", img: "" },
      { name: "Giallo Orion",      hex: "#f0c000", img: "" },
      { name: "Verde Mantis",      hex: "#2a5818", img: "" },
      { name: "Arancio Borealis",  hex: "#d45a00", img: "" },
      { name: "Blu Astraeus",      hex: "#1a2a5a", img: "" },
      { name: "Grigio Lynx",       hex: "#6a6a6a", img: "" },
    ],
    specs: {
      engine: "4.0L V8 Twin-Turbo",
      power: "657 hp",
      torque: "627 lb-ft",
      transmission: "8-Speed Auto",
      drivetrain: "AWD",
      seats: 5,
    },
    description: "The world's first Super Sport Utility Vehicle. The Urus S delivers Lamborghini's racing DNA in a package that seats five and conquers any terrain. Carbon ceramic brakes, active torque vectoring, and a soundtrack that announces your arrival from a mile away.",
    images: [
      "https://images.unsplash.com/photo-1621135802920-133df287f89c?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&q=90&auto=format&fit=crop",
    ],
  },
  {
    id: 9,
    name: "Ferrari SF90 Stradale",
    year: 2023,
    price: 507000,
    mileage: 2800,
    fuel: "Hybrid",
    category: "Sport",
    brand: "Ferrari",
    available: true,
    badge: "Exotic",
    horsepower: 986,
    torque: 590,
    engine: "4.0L V8 Twin-Turbo + 3 Electric Motors",
    transmission: "8-Speed DCT",
    drivetrain: "AWD",
    topSpeed: 211,
    zeroToSixty: 2.5,
    fuelType: "Hybrid",
    mpg: "16 city / 19 hwy",
    range: "15 miles electric",
    seating: 2,
    infotainment: "Ferrari HD Cluster 16\" + HUD",
    safetyFeatures: ["Ferrari Dynamic Enhancer+", "Side Slip Control 6.1", "ABS evo", "Electronic Diff"],
    colors: [
      { name: "Rosso Corsa",       hex: "#c8001e", img: "" },
      { name: "Nero Daytona",      hex: "#0a0a0a", img: "" },
      { name: "Giallo Modena",     hex: "#f0c000", img: "" },
      { name: "Bianco Avus",       hex: "#f4f4f0", img: "" },
      { name: "Blu Pozzi",         hex: "#1a2a5a", img: "" },
      { name: "Verde Dino",        hex: "#1a4a28", img: "" },
      { name: "Grigio Silverstone",hex: "#8a8a8a", img: "" },
    ],
    specs: {
      engine: "4.0L V8 + 3 Electric Motors",
      power: "986 hp",
      torque: "590 lb-ft",
      transmission: "8-Speed DCT",
      drivetrain: "AWD",
      seats: 2,
    },
    description: "Ferrari's most powerful road car ever. The SF90 Stradale combines a twin-turbo V8 with three electric motors to produce 986 hp — enough to reach 60 mph in 2.5 seconds and 211 mph flat out. A masterpiece of Maranello engineering.",
    images: [
      "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=90&auto=format&fit=crop",
    ],
  },
  {
    id: 10,
    name: "Rolls-Royce Ghost",
    year: 2024,
    price: 332000,
    mileage: 900,
    fuel: "Petrol",
    category: "Sedan",
    brand: "Rolls-Royce",
    available: true,
    badge: "Premium",
    horsepower: 563,
    torque: 627,
    engine: "6.75L V12 Twin-Turbo",
    transmission: "8-Speed Automatic",
    drivetrain: "AWD",
    topSpeed: 155,
    zeroToSixty: 4.6,
    fuelType: "Premium Petrol",
    mpg: "13 city / 20 hwy",
    seating: 5,
    infotainment: "Spirit of Ecstasy Rotary Controller + 10.25\" Display",
    safetyFeatures: ["Night Vision", "Alertness Assistant", "Active Cruise Control", "Surround View Camera"],
    colors: [
      { name: "Black Diamond",       hex: "#0a0a0a", img: "" },
      { name: "Arctic White",        hex: "#f6f4f0", img: "" },
      { name: "Bohemian Red",        hex: "#6a0a0a", img: "" },
      { name: "Salamanca Blue",      hex: "#0a1838", img: "" },
      { name: "Silver Sand",         hex: "#c0b8a8", img: "" },
      { name: "Gunmetal",            hex: "#3a3a3a", img: "" },
      { name: "Twilight Purple",     hex: "#2a1a3a", img: "" },
    ],
    specs: {
      engine: "6.75L V12 Twin-Turbo",
      power: "563 hp",
      torque: "627 lb-ft",
      transmission: "8-Speed Auto",
      drivetrain: "AWD",
      seats: 5,
    },
    description: "Post Opulence. The Ghost is the most technologically advanced Rolls-Royce ever created. An all-aluminium spaceframe, planar suspension system, and a cabin of absolute silence — the Ghost does not merely transport you, it elevates you.",
    images: [
      "https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1562911791-c7a97b729ec5?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=1200&q=90&auto=format&fit=crop",
    ],
  },
  {
    id: 11,
    name: "McLaren 720S",
    year: 2023,
    price: 299000,
    mileage: 4100,
    fuel: "Petrol",
    category: "Sport",
    brand: "McLaren",
    available: true,
    badge: "Exotic",
    horsepower: 710,
    torque: 568,
    engine: "4.0L V8 Twin-Turbo",
    transmission: "7-Speed SSG",
    drivetrain: "RWD",
    topSpeed: 212,
    zeroToSixty: 2.8,
    fuelType: "Premium Petrol",
    mpg: "15 city / 22 hwy",
    seating: 2,
    infotainment: "McLaren IRIS 8\" Touchscreen",
    safetyFeatures: ["McLaren Brake Steer", "Variable Drift Control", "ABS", "ESC"],
    colors: [
      { name: "Onyx Black",        hex: "#0a0a0a", img: "" },
      { name: "Silica White",      hex: "#f4f4f0", img: "" },
      { name: "Papaya Spark",      hex: "#e87020", img: "" },
      { name: "Lantana Purple",    hex: "#481868", img: "" },
      { name: "Volcano Orange",    hex: "#c84800", img: "" },
      { name: "Supernova Silver",  hex: "#b0b0b0", img: "" },
      { name: "Azores Blue",       hex: "#1a3060", img: "" },
    ],
    specs: {
      engine: "4.0L V8 Twin-Turbo",
      power: "710 hp",
      torque: "568 lb-ft",
      transmission: "7-Speed SSG",
      drivetrain: "RWD",
      seats: 2,
    },
    description: "Pure McLaren. The 720S is built around a carbon fibre MonoCell II chassis that weighs just 1,283 kg. Dihedral doors, active aerodynamics, and a twin-turbo V8 that delivers 710 hp — the 720S is the benchmark for mid-engine supercars.",
    images: [
      "https://images.unsplash.com/photo-1621135802920-133df287f89c?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=1200&q=90&auto=format&fit=crop",
    ],
  },
  {
    id: 12,
    name: "Aston Martin DB12",
    year: 2024,
    price: 245000,
    mileage: 1800,
    fuel: "Petrol",
    category: "Sport",
    brand: "Aston Martin",
    available: true,
    badge: "New Arrival",
    horsepower: 671,
    torque: 590,
    engine: "4.0L V8 Twin-Turbo",
    transmission: "8-Speed Automatic",
    drivetrain: "RWD",
    topSpeed: 202,
    zeroToSixty: 3.5,
    fuelType: "Premium Petrol",
    mpg: "16 city / 23 hwy",
    seating: 4,
    infotainment: "Aston Martin COMAND 10.25\" + 12.3\" Driver Display",
    safetyFeatures: ["Autonomous Emergency Braking", "Lane Departure Warning", "Blind Spot Monitoring", "Rear Camera"],
    colors: [
      { name: "Onyx Black",        hex: "#0a0a0a", img: "" },
      { name: "Iridescent Lime",   hex: "#8a9818", img: "" },
      { name: "Lunar White",       hex: "#f4f4f0", img: "" },
      { name: "Hyper Red",         hex: "#aa0a0a", img: "" },
      { name: "Satin Xenon Grey",  hex: "#5a5a5a", img: "" },
      { name: "Midnight Blue",     hex: "#0a1a38", img: "" },
      { name: "Cognac Tan",        hex: "#8a5a28", img: "" },
    ],
    specs: {
      engine: "4.0L V8 Twin-Turbo",
      power: "671 hp",
      torque: "590 lb-ft",
      transmission: "8-Speed Auto",
      drivetrain: "RWD",
      seats: 4,
    },
    description: "The world's first Super Tourer. The DB12 represents a complete reinvention of the Aston Martin grand tourer — 671 hp, 202 mph, and a cabin that blends British craftsmanship with cutting-edge technology. The most powerful, most dynamic DB ever made.",
    images: [
      "https://images.unsplash.com/photo-1542362567-b07e54358753?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1563720223185-11003d516935?w=1200&q=90&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=90&auto=format&fit=crop",
    ],
  },
];

export function getCarById(id: number) {
  return CARS.find((c) => c.id === id) ?? null;
}

export function getSimilarCars(car: { id: number; category: string; brand: string }, limit = 3) {
  return CARS.filter((c) => c.id !== car.id && (c.category === car.category || c.brand === car.brand)).slice(0, limit);
}
